### ISSUE TITLE
passing :delete as the final param wont work in ecto 3

### ISSUE THREAD

**Issue by sushant12** [andkar73/nested_forms#1]
https://github.com/andkar73/nested_forms/blob/master/lib/nested_forms/users/post.ex#L16

That line of code would only work for Ecto 2 . If you looked into Ecto 3, it would not work anymore. https://github.com/elixir-ecto/ecto/blob/v3.1/lib/ecto/changeset.ex#L478.

What could be done is move the :delete atom to 3rd param `user |> cast(attrs, [:email, :delete])`

**Comment by andkar73** [comment]
Thanks for the feedback. You are absolutely right.
